# This is a basic workflow to help you get started with Actions

name: FlutterCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ web-test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        # flutter-version: '3.7.7' # you can also specify exact version of flutter
        channel: 'stable' # 'dev', 'alpha', 'master', default to: 'stable'
    
    - name: Get dependencies
      run: flutter pub get

    - name: Flutter doctor
      run: flutter doctor
    
    - name: Build Web
      run: flutter build web
    
    - name: Upload WEB artifact 
      uses: actions/upload-artifact@v1
      with:
        name: web-app
        path: build/web
